"""Plain-language tooltips for Streamlit help= kwargs."""

HELP = {
    "strategy_return": "Total profit or loss if you had followed the model's signals over the test period, after trading costs. Days in cash earn the risk-free rate (~6%/yr, like a liquid fund). Example: +12% means ₹100 would have become ₹112.",
    "buy_hold": "What you'd have made by simply buying on day one and holding — no signals, no trading. The benchmark: if the strategy can't beat this, the model adds no value.",
    "sharpe": "Return earned ABOVE the risk-free rate (~6%/yr — what cash in a liquid fund earns) per unit of risk taken, annualized. Was the profit worth the rollercoaster? Below 0 = worse than cash, 0–1 = weak, above 1 = good, above 2 = excellent.",
    "max_drawdown": "The worst peak-to-bottom fall of your money. -30% means at some point you'd have been down 30% from your highest point — a gut-check for pain tolerance.",
    "win_rate": "Of all days the strategy held the stock (including the overnight gap on an exit day), the percentage that ended up. Around 50% is a coin flip.",
    "exposure": "Share of days invested in the stock rather than sitting in cash. 60% = in the market 6 days out of 10.",
    "trades": "Number of times the strategy bought in. More trades = more costs, so fewer, better trades win.",
    "cost": "Typical all-in cost of one buy + one sell for this stock. For NSE delivery: STT 0.1% on each leg, 0.015% stamp duty on the buy, exchange/SEBI fees + GST, a ₹15.93 DP charge per sell (on a ₹1 lakh trade), plus bid-ask spread and market impact that grow as the stock's traded value shrinks. Thin small-caps can cost several percent per round trip.",
    "accuracy": "How often the model's up/down guess was right on data it never saw in training. Only meaningful if it beats the baseline →",
    "baseline": "What a 'dumb' model scores by always predicting the most common outcome. If accuracy doesn't beat this, the model learned nothing.",
    "precision": "When the model said 'up', how often it was right. High precision = trustworthy BUY calls.",
    "recall": "Of all days the price actually rose, how many the model caught. High recall = it doesn't miss rallies.",
    "rsi": "Relative Strength Index — a 0–100 speedometer of buying vs selling pressure. Above 70: possibly overbought. Below 30: possibly oversold.",
    "last_close": "Most recent closing price, with change vs the previous trading day.",
    "prob_up": "The model's estimated chance that the price makes a meaningful up move over this horizon. 50% = coin flip; further from 50% = more conviction.",
    "rating": "Fixed probability band: Strong Buy >80%, Buy 65–80%, Neutral 45–65%, Sell <45%. This is separate from the trading signal, which uses tuned entry/exit thresholds.",
    "risk_score": "1 (calm) to 10 (wild), blending the stock's volatility, daily trading range, and worst fall of the past year. Higher risk = consider a smaller position size.",
    "horizon_accuracy": "Each horizon has its own model, tested on recent data it never trained on. Longer horizons overlap heavily, so treat their accuracy as optimistic.",
    "model_type": "Ensemble averages a regularized neural net, XGBoost (or HistGBDT) and a Random Forest — usually the most reliable choice. LSTM/GRU read the last 20 days as a sequence; slower to train and rarely better on this little data, but worth comparing in the Walk-Forward tab.",
    "support": "A price floor where the stock repeatedly stopped falling and bounced (recent swing lows). Buyers tend to step in here; a fall through it is a warning sign.",
    "resistance": "A price ceiling where the stock repeatedly stopped rising and turned back (recent swing highs). Sellers tend to appear here; a break above it is often bullish.",
    "entry": "The planning reference — the latest close. A real order fills at the next session's open, which can gap above or below this.",
    "stop_loss": "The price at which you exit to cap the loss if the trade goes wrong. Placed below support or 1.5× the stock's typical daily range, so normal wiggle doesn't knock you out.",
    "target": "The price at which you'd take profit — the nearest resistance, or 3× the typical daily range if no resistance is close enough to be worth the risk.",
    "reward_risk": "How much you stand to gain per rupee risked. 1:2.5 means risking ₹1 to potentially make ₹2.50. Professionals rarely take trades below 1:1.5.",
    "capital": "Your total trading capital — the pot you size every position from.",
    "risk_per_trade": "The percentage of capital you accept losing if this one trade hits its stop loss. The classic rule is 1–2%: it takes dozens of consecutive losses to do serious damage.",
    "position_shares": "Shares to buy so that hitting the stop loses exactly your chosen risk amount: (capital × risk%) ÷ (entry − stop). Capped so the position never costs more than your capital.",
    "calibrate": "Remaps the model's probabilities so they match reality: if the raw model says '75%' but such days only rise 60% of the time, calibrated output says 60%. Makes percentages honest; doesn't make the model smarter, and on limited data can slightly blur sharp predictions.",
    "brier": "Average squared error of the probabilities (lower = better). The number to beat is the baseline — what you'd score by always predicting the historical average. Beating it means the probabilities carry real information.",
    "ece": "Expected Calibration Error: the average gap between stated probability and observed frequency. 0.02 = percentages are trustworthy; 0.10+ = when the model says 70%, don't believe 70%.",
    "journal": "Backtests look backward; the journal looks forward. Each logged signal is later scored against real prices. Storage is per-user: local CSV by default, or Supabase when configured in secrets (survives Streamlit Cloud restarts).",
    "target_rate": "Of resolved BUY plans, the share that reached the target before hitting the stop.",
    "journal_status": "Fills are simulated like a real order: bought at the next session's open. TARGET HIT / STOP HIT: which level was reached first — a gap through the level exits at the open, not at the level. EXPIRED: neither within 20 trading days, sold at that day's close. NO FILL: the next session was locked at the upper circuit, or opened already past the stop or target. OPEN: still running. Returns are after costs.",
    "scanner": "Screener: load precomputed rankings (offline job) for instant results, or walk the full watchlist live in batches of 80. Probabilities come from the 10-day global model; the shortlist takes the top slice of the liquid universe, ranked by Buy Score. The Screen column is the old absolute call (BUY above 0.55) and is shown for reference. Screen only — open a stock for the full Signal. Not investment advice.",
    "buy_score": "0–100 composite for long candidates: ~50% model probability (10-day), ~20% accuracy vs baseline, ~12% lower risk, ~12% trade-plan R:R, ~6% proximity to support. Ranking aid only.",
    "entry_rule": "Top % of universe (recommended): shortlist the names whose 10-day probability ranks in the top slice of today's liquid, scored stocks. It adapts to the model's base rate (~40% of 10-day windows clear the 'meaningful up move' bar), so the list is never empty. Absolute: the old rule — probability above a fixed cutoff — which rarely fires because probabilities cluster around the base rate.",
    "review_cadence": "In an out-of-sample test (2020–26, 2,081 NSE stocks, real costs), reviewing the shortlist every ~2 weeks kept costs near 9%/yr; weekly reviews on a 1-day signal cost 24%/yr and lost money. Even the best setup (+15%/yr) trailed the Nifty 500 (+18%/yr) — treat the list as research leads, not a strategy.",
    "scan_to_support": "How far the current price sits above its nearest support level. Small = near a floor that has held before; negative would mean below all detected supports.",
    "scan_to_resistance": "How far the nearest ceiling sits above the current price. Small = close to a level where rallies have stalled before.",
    "refresh": "Clears all cached data and models, then reloads with the latest prices. Everything retrains on the next view, so the first load after refreshing is slow — use when you specifically need today's latest close.",
    "buys_only": "Show only BUY screen calls in the full ranking table.",
    "benchmark": "Generates hundreds of random strategies that hold for the same number of days as the model, then shows where the model ranks. Above the 90th percentile = a real edge; near the 50th = no better than luck; the bell curve shows the random crowd.",
    "global_model": "When trained, the global model is one model fitted on the pooled history of many stocks (time-ordered offline train) instead of ~1,200 rows for one name — usually steadier on short histories. Weights may include this stock; thresholds stay stock-specific. Prefer Walk-Forward for a stricter edge check.",
    "execution": "How the backtest trades: each signal is formed at the close and filled at the NEXT session's open, so overnight gaps belong to the position you already held. Costs and slippage are charged on every buy and sell, and orders are blocked on days the stock is locked at its upper (can't buy) or lower (can't sell) circuit.",
    "plan_backtest": "Simulates exactly what the Plan tab tells you to do: on each BUY signal, that day's stop and target, filled at the next open and exited at the stop, the target, or after 20 trading days — whichever comes first. One trade at a time.",
    "profit_factor": "Total gains from winning trades ÷ total losses from losing trades. Above 1 = the winners paid for the losers; 1.5+ is solid.",
    "portfolio_backtest": "Runs the screener as a real portfolio on years the model never saw: every week, buy the top names by Buy Score, sell names that drop out, pay real costs — and compare with simply owning the index.",
    "traded_value": "Median daily traded value (price × shares traded) over the last 20 sessions, in ₹ crore. Below ~₹1 Cr/day, spreads are wide, your own order moves the price, and you may not be able to exit when you want.",
    "price_band": "The stock's circuit band, inferred from its most recent locked session (it traded at one price after moving exactly ±2/5/10/20%). A 2% or 5% band usually means exchange surveillance (ASM/GSM), trade-to-trade settlement, or a thinly traded scrip. Blank = no recent lock (most liquid names).",
    "survivorship": "The global model was trained on stocks that are listed today. Companies that were delisted or collapsed are missing from its history, so its accuracy — and any pooled backtest — looks better than live trading will.",
    "use_global": "A global model is available. Keep it on for pooled-data predictions, or untick to train a per-stock model on the fly and compare the two in the Walk-Forward tab. Global accuracy on this page is indicative, not fully out-of-sample.",
}
