"""Plain-language tooltips for Streamlit help= kwargs."""

HELP = {
    "strategy_return": "Total profit or loss if you had followed the model's signals over the test period, after trading costs. Example: +12% means ₹100 would have become ₹112.",
    "buy_hold": "What you'd have made by simply buying on day one and holding — no signals, no trading. The benchmark: if the strategy can't beat this, the model adds no value.",
    "sharpe": "Return earned per unit of risk taken (annualized). Was the profit worth the rollercoaster? Below 0 = losing, 0–1 = weak, above 1 = good, above 2 = excellent.",
    "max_drawdown": "The worst peak-to-bottom fall of your money. -30% means at some point you'd have been down 30% from your highest point — a gut-check for pain tolerance.",
    "win_rate": "Of all days the strategy held the stock, the percentage that ended up. Around 50% is a coin flip.",
    "exposure": "Share of days invested in the stock rather than sitting in cash. 60% = in the market 6 days out of 10.",
    "trades": "Number of times the strategy bought in. More trades = more costs, so fewer, better trades win.",
    "cost": "Brokerage, taxes and slippage charged on every position change. 0.10% per change ≈ 0.2% for a full round trip.",
    "accuracy": "How often the model's up/down guess was right on data it never saw in training. Only meaningful if it beats the baseline →",
    "baseline": "What a 'dumb' model scores by always predicting the most common outcome. If accuracy doesn't beat this, the model learned nothing.",
    "precision": "When the model said 'up', how often it was right. High precision = trustworthy BUY calls.",
    "recall": "Of all days the price actually rose, how many the model caught. High recall = it doesn't miss rallies.",
    "rsi": "Relative Strength Index — a 0–100 speedometer of buying vs selling pressure. Above 70: possibly overbought. Below 30: possibly oversold.",
    "last_close": "Most recent closing price, with change vs the previous trading day.",
    "prob_up": "The model's estimated chance that the price makes a meaningful up move over this horizon. 50% = coin flip; further from 50% = more conviction.",
    "rating": "Fixed probability band: Strong Buy >80%, Buy 65–80%, Neutral 45–65%, Sell <45%. This is separate from the trading signal, which uses tuned entry/exit thresholds.",
    "risk_score": "1 (calm) to 10 (wild), blending the stock's volatility, daily trading range, and worst fall of the past year. Higher risk = consider a smaller position size.",
    "horizon_accuracy": "Each horizon has its own model, tested on recent data it never trained on. Longer horizons overlap heavily, so treat their accuracy as optimistic.",
    "model_type": "Ensemble averages a regularized neural net, XGBoost (or HistGBDT) and a Random Forest — usually the most reliable choice. LSTM/GRU read the last 20 days as a sequence; slower to train and rarely better on this little data, but worth comparing in the Walk-Forward tab.",
    "support": "A price floor where the stock repeatedly stopped falling and bounced (recent swing lows). Buyers tend to step in here; a fall through it is a warning sign.",
    "resistance": "A price ceiling where the stock repeatedly stopped rising and turned back (recent swing highs). Sellers tend to appear here; a break above it is often bullish.",
    "entry": "The price you'd pay to open the trade — here, the latest closing price.",
    "stop_loss": "The price at which you exit to cap the loss if the trade goes wrong. Placed below support or 1.5× the stock's typical daily range, so normal wiggle doesn't knock you out.",
    "target": "The price at which you'd take profit — the nearest resistance, or 3× the typical daily range if no resistance is close enough to be worth the risk.",
    "reward_risk": "How much you stand to gain per rupee risked. 1:2.5 means risking ₹1 to potentially make ₹2.50. Professionals rarely take trades below 1:1.5.",
    "capital": "Your total trading capital — the pot you size every position from.",
    "risk_per_trade": "The percentage of capital you accept losing if this one trade hits its stop loss. The classic rule is 1–2%: it takes dozens of consecutive losses to do serious damage.",
    "position_shares": "Shares to buy so that hitting the stop loses exactly your chosen risk amount: (capital × risk%) ÷ (entry − stop). Capped so the position never costs more than your capital.",
    "calibrate": "Remaps the model's probabilities so they match reality: if the raw model says '75%' but such days only rise 60% of the time, calibrated output says 60%. Makes percentages honest; doesn't make the model smarter, and on limited data can slightly blur sharp predictions.",
    "brier": "Average squared error of the probabilities (lower = better). The number to beat is the baseline — what you'd score by always predicting the historical average. Beating it means the probabilities carry real information.",
    "ece": "Expected Calibration Error: the average gap between stated probability and observed frequency. 0.02 = percentages are trustworthy; 0.10+ = when the model says 70%, don't believe 70%.",
    "journal": "Backtests look backward; the journal looks forward. Each logged signal is later scored against real prices. Storage is per-user: local CSV by default, or Supabase when configured in secrets (survives Streamlit Cloud restarts).",
    "target_rate": "Of resolved BUY plans, the share that reached the target before hitting the stop.",
    "journal_status": "TARGET HIT / STOP HIT: which level the price touched first. EXPIRED: neither within 20 trading days — scored at that day's close. OPEN: still running.",
    "scanner": "Screener panels: Top picks, Full ranking, Data source, Alerts. Sticky filters include probability, risk, sector (from selected stock name), and sort. Live scan shows Batch N of M. Screen ≠ full Signal — open a stock for the real call. Not investment advice.",
    "buy_score": "0–100 composite for long candidates: ~50% model probability, ~20% accuracy vs baseline, ~12% lower risk, ~12% trade-plan R:R, ~6% proximity to support. Ranking aid only.",
    "scan_to_support": "How far the current price sits above its nearest support level. Small = near a floor that has held before; negative would mean below all detected supports.",
    "scan_to_resistance": "How far the nearest ceiling sits above the current price. Small = close to a level where rallies have stalled before.",
    "refresh": "Clears all cached data and models, then reloads with the latest prices. Everything retrains on the next view, so the first load after refreshing is slow — use when you specifically need today's latest close.",
    "buys_only": "Show only BUY screen calls in the full ranking table.",
    "benchmark": "Generates hundreds of random strategies that hold for the same number of days as the model, then shows where the model ranks. Above the 90th percentile = a real edge; near the 50th = no better than luck; the bell curve shows the random crowd.",
    "global_model": "When trained, the global model is one model fitted on the pooled history of many stocks (time-ordered offline train) instead of ~1,200 rows for one name — usually steadier on short histories. Weights may include this stock; thresholds stay stock-specific. Prefer Walk-Forward for a stricter edge check.",
    "use_global": "A global model is available. Keep it on for pooled-data predictions, or untick to train a per-stock model on the fly and compare the two in the Walk-Forward tab. Global accuracy on this page is indicative, not fully out-of-sample.",
    "report_download": "One-click CSV or PDF of this stock's signal, risk, trade plan, and hold-out metrics. For personal notes only — not a research report or recommendation.",
    "alerts": "Optional Telegram/email when top BUY screens clear your min Buy Score filters. Configure [alerts] in Streamlit secrets. De-dupes per rankings snapshot so the same names are not spammed.",
}
